### ISSUE TITLE
Superfluous initvar()

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/calendar#8]
There is a [superfluous initvar()](https://github.com/cmsimple-xh/calendar/blob/1.4.8/admin.php#L27) which triggers a deprecation notice under CMSimple_XH 1.7.0.

**Comment by pigsound** [comment]
this bug is also triggered in CMSimple_XH 1.7.2.

**Comment by cmb69** [comment]
Simply deleting [this line](https://github.com/cmsimple-xh/calendar/blob/1.4.8/admin.php#L27) should resolve the issue.
